# This MachineConfig demonstrates appending content to an existing file
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 99-ignition-files-overwrite
spec:
  config:
    ignition:
      version: 3.1.0
    storage:
      files:
        - contents:
            source: data:text/plain;charset=utf-8;base64,aGVsbG8gb3RoZXIgd29ybGRzCg==
          filesystem: root
          path: /var/srv/hello-world.txt
          overwrite: true
