# This MachineConfig demonstrates the minimal requirements for writing out a
# file to the node
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 99-ignition-files-minimal
spec:
  config:
    ignition:
      version: 3.1.0
    storage:
      files:
        - contents:
            source: data:text/plain;charset=utf-8;base64,aGVsbG8gd29ybGQK
          filesystem: root
          path: /var/srv/hello-world.txt
