# This MachineConfig demonstrates overwriting an existing file
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 99-ignition-files-attributes
spec:
  config:
    ignition:
      version: 3.1.0
    storage:
      files:
        - contents:
            source: data:text/plain;charset=utf-8;base64,b3duZWQgYnkgcm9vdAo=
          filesystem: root
          path: /var/srv/owned-by-root.txt
          mode: 0644
          user:
            id: 0
          group:
            name: root
