apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 99-worker-namserver
spec:
  config:
    ignition:
      version: 2.2.0
    storage:
      files:
      - contents:
          source: data:text/plain;charset=utf-8;base64,c2VhcmNoIHVzLXdlc3QtMS5jb21wdXRlLmludGVybmFsCm5hbWVzZXJ2ZXIgMTAuMC4wLjIKbmFtZXNlcnZlciAxLjEuMS4xCm5hbWVzZXJ2ZXIgOC44LjguOAo=
        filesystem: root
        mode: 0644
        path: /etc/resolv.conf
