apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 61-nosmt-kargs
spec:
    config:
        ignition:
            version: 2.2.0
    kernelArguments:
        - nosmt
