apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 70-multi-kargs
spec:
    kernelArguments:
      - nvme_core.io_timeout=4294967295
      - foo=bar
      - bar=baz
