apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 70-duplicate-foobar
spec:
    kernelArguments:
      - foo=bar
