apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 99-new-master-sshkey
spec:
  config:
    ignition:
      version: 3.1.0
    passwd:
      users:
      - name: core
        sshAuthorizedKeys:
        - |
          ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIveEaMRWZJDSkkMaIX8WC4Vtk81KaXv8weJxAjX4VeU
